version: '3'
services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    env_file: .env.development
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
#    volumes:
#      - ./docker/minio:/data
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: .env.development
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./configs/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    command: /nsqd --broadcast-address=127.0.0.1 --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"